### ISSUE TITLE
Agree on file structure

### ISSUE THREAD

**Issue by matthall8** [FACN4/week9-the-a-team#10]
Agree on the file structure and where the components live.

**Comment by tawfiknasser** [comment]
![jjjjjjjjjjjjjjjjjjjj](https://user-images.githubusercontent.com/36166288/44720843-c764ed80-aad0-11e8-83aa-37dd36693b09.jpeg)

**Comment by tawfiknasser** [comment]
![jkjkkk](https://user-images.githubusercontent.com/36166288/44720944-0dba4c80-aad1-11e8-9a7b-884382a09c27.png)

**Comment by tawfiknasser** [comment]
agreed
