### ISSUE TITLE
Base logic for board

### ISSUE THREAD

**Issue by matthall8** [FACN4/week9-the-a-team#5]
Create the base javascript logic for the board

**Comment by tawfiknasser** [comment]
built  game class ,
the constructor build the board with border.

`changeValue (x,y,who){
  // who can be 1 or 2
  this.board[x][y]=who;
}`

> who 
should be 1 for the first player  & 2 for the second player
0 is no one ,
9 for the border.

**Comment by matthall8** [comment]
Base written in the current file.
