### ISSUE TITLE
<br /> in Board

### ISSUE THREAD

**Issue by jema28** [FACN4/week9-the-a-team#62]
Is there a reason for the breaks in board? I would do this in CSS. 

<img width="1000" alt="screen shot 2018-08-30 at 10 35 23" src="https://user-images.githubusercontent.com/25960351/44836798-90154e80-ac40-11e8-9512-0c06dbcb6f7a.png">

**Comment by matthall8** [comment]
This has been fixed in the latest commit. Can you review and close if you agree.
